#!/usr/bin/env python3
"""gen_pipe_test.py -- emit a hazard-free random RV32I ALU program (M2).

The program is straight-line (no branches) and inserts 3 NOPs after every real
instruction, so it is guaranteed hazard-free for a pipeline with no forwarding
or stalls. Each result is folded (XOR) into an accumulator that is written to
`tohost` as a 32-bit signature. Running the same seed on the single-cycle
reference and on the pipeline must yield the same signature.

    python3 gen_pipe_test.py <seed> [n_ops] > prog.S

Deterministic in the seed, so committed seeds give reproducible results.
"""
import random
import sys

R_OPS = ["add", "sub", "and", "or", "xor", "sll", "srl", "sra", "slt", "sltu"]
I_OPS = ["addi", "andi", "ori", "xori", "slti", "sltiu"]
SHIFT_I = ["slli", "srli", "srai"]

# General-purpose pool; s0 (accumulator) and s1 (address) are reserved.
POOL = ["t0", "t1", "t2", "t3", "t4", "t5", "t6",
        "a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7",
        "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11"]

P = "nop; nop; nop"


def main() -> int:
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    n_ops = int(sys.argv[2]) if len(sys.argv) > 2 else 40
    rng = random.Random(seed)

    L = []
    L.append("// auto-generated by tools/gen_pipe_test.py -- do not edit")
    L.append(f"// seed={seed} n_ops={n_ops}")
    L.append("    .section .text.init")
    L.append("    .globl _start")
    L.append("_start:")
    L.append(f"    li s0, 0 ; {P}")
    # seed the pool with random 12-bit immediates
    for r in POOL:
        L.append(f"    li {r}, {rng.randint(-2048, 2047)} ; {P}")

    for _ in range(n_ops):
        kind = rng.choice(["r", "i", "sh"])
        rd = rng.choice(POOL)
        if kind == "r":
            op, a, b = rng.choice(R_OPS), rng.choice(POOL), rng.choice(POOL)
            L.append(f"    {op} {rd}, {a}, {b} ; {P}")
        elif kind == "i":
            op, a, imm = rng.choice(I_OPS), rng.choice(POOL), rng.randint(-2048, 2047)
            L.append(f"    {op} {rd}, {a}, {imm} ; {P}")
        else:
            op, a, sh = rng.choice(SHIFT_I), rng.choice(POOL), rng.randint(0, 31)
            L.append(f"    {op} {rd}, {a}, {sh} ; {P}")
        L.append(f"    xor s0, s0, {rd} ; {P}")

    L.append("    lui  s1, %hi(tohost) ; " + P)
    L.append("    addi s1, s1, %lo(tohost) ; " + P)
    L.append("    sw   s0, 0(s1) ; " + P)
    L.append("1:  j 1b")
    L.append('    .section .tohost, "aw", @progbits')
    L.append("    .align 6")
    L.append("    .globl tohost")
    L.append("tohost: .dword 0")
    L.append("    .globl fromhost")
    L.append("fromhost: .dword 0")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
