#!/usr/bin/env python3
"""gen_pipe_test.py -- emit a random RV32I program for differential testing.

Two modes:
  hazard-free (default): straight-line ALU ops with 3 NOPs after every real
    instruction -- safe for the M2 pipeline (no forwarding/stalls).
  --hazard: no padding, dense register reuse, and loads/stores mixed in --
    exercises forwarding, the load-use stall, and store-data forwarding (M3).

Each result is folded (XOR) into an accumulator written to `tohost` as a 32-bit
signature; the same seed must produce the same signature on the single-cycle
reference and on the pipeline.

    python3 gen_pipe_test.py <seed> [n_ops] [--hazard] > prog.S

Deterministic in the seed, so committed seeds give reproducible results.
"""
import random
import sys

R_OPS = ["add", "sub", "and", "or", "xor", "sll", "srl", "sra", "slt", "sltu"]
I_OPS = ["addi", "andi", "ori", "xori", "slti", "sltiu"]
SHIFT_I = ["slli", "srli", "srai"]

# General-purpose pool; reserved: s0 (accumulator), s1 (tohost address),
# s2 (scratch base in hazard mode).
POOL = ["t0", "t1", "t2", "t3", "t4", "t5", "t6",
        "a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7",
        "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11"]

P = "nop; nop; nop"


def main() -> int:
    args = [a for a in sys.argv[1:] if a != "--hazard"]
    hazard = "--hazard" in sys.argv[1:]
    seed = int(args[0]) if len(args) > 0 else 0
    n_ops = int(args[1]) if len(args) > 1 else 40
    rng = random.Random(seed)
    pad = "" if hazard else " ; " + P

    L = []
    L.append("// auto-generated by tools/gen_pipe_test.py -- do not edit")
    L.append(f"// seed={seed} n_ops={n_ops} hazard={hazard}")
    L.append("    .section .text.init")
    L.append("    .globl _start")
    L.append("_start:")
    L.append(f"    li s0, 0{pad}")
    # seed the pool with random 12-bit immediates
    for r in POOL:
        L.append(f"    li {r}, {rng.randint(-2048, 2047)}{pad}")
    if hazard:
        # scratch base for load/store traffic (a small pool keeps reuse dense)
        L.append("    lui  s2, %hi(scratch)")
        L.append("    addi s2, s2, %lo(scratch)")

    # In hazard mode, bias register choice towards recent destinations so
    # back-to-back RAW chains are common.
    recent = []

    def pick_src(rng):
        if hazard and recent and rng.random() < 0.6:
            return rng.choice(recent[-3:])
        return rng.choice(POOL)

    kinds = ["r", "i", "sh"] + (["ld", "st"] if hazard else [])
    for _ in range(n_ops):
        kind = rng.choice(kinds)
        rd = rng.choice(POOL)
        if kind == "r":
            op, a, b = rng.choice(R_OPS), pick_src(rng), pick_src(rng)
            L.append(f"    {op} {rd}, {a}, {b}{pad}")
        elif kind == "i":
            op, a, imm = rng.choice(I_OPS), pick_src(rng), rng.randint(-2048, 2047)
            L.append(f"    {op} {rd}, {a}, {imm}{pad}")
        elif kind == "sh":
            op, a, sh = rng.choice(SHIFT_I), pick_src(rng), rng.randint(0, 31)
            L.append(f"    {op} {rd}, {a}, {sh}{pad}")
        elif kind == "st":
            src, off = pick_src(rng), 4 * rng.randint(0, 7)
            L.append(f"    sw {src}, {off}(s2)")
        else:  # ld -- immediately consumed below, exercising the load-use stall
            off = 4 * rng.randint(0, 7)
            L.append(f"    lw {rd}, {off}(s2)")
        if kind != "st":
            L.append(f"    xor s0, s0, {rd}{pad}")
            recent.append(rd)

    L.append(f"    lui  s1, %hi(tohost){pad}")
    L.append(f"    addi s1, s1, %lo(tohost){pad}")
    L.append(f"    sw   s0, 0(s1){pad}")
    L.append("1:  j 1b")
    if hazard:
        L.append("    .section .data")
        L.append("    .align 4")
        L.append("scratch:")
        L.append("    .space 64")
    L.append('    .section .tohost, "aw", @progbits')
    L.append("    .align 6")
    L.append("    .globl tohost")
    L.append("tohost: .dword 0")
    L.append("    .globl fromhost")
    L.append("fromhost: .dword 0")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
