#!/usr/bin/env python3
"""perf_report.py -- turn measured benchmark results into a Markdown report.

Reads the CSV written by `scripts/run_benchmarks.sh --csv` and produces a
report with CPI per predictor mode, speedup over the unpredicted baseline,
branch-mispredict rates, and a stall-cycle breakdown. Every number is derived
arithmetically from measured counters -- nothing is modelled or estimated.

    python3 perf_report.py results.csv -o report.md
"""
import argparse
import csv
from collections import defaultdict

MODES = ["off", "bimodal", "gshare"]


def load(path):
    rows = defaultdict(dict)
    with open(path) as f:
        for r in csv.DictReader(f):
            for k in ("cycles", "retired", "stall_loaduse", "stall_mdu",
                      "redirects", "branches", "taken", "mispredicts"):
                r[k] = int(r[k])
            r["cpi"] = float(r["cpi"])
            rows[r["benchmark"]][r["mode"]] = r
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csv")
    ap.add_argument("-o", "--out", default="-")
    a = ap.parse_args()

    data = load(a.csv)
    L = []
    L.append("# Measured performance report")
    L.append("")
    L.append("Generated by `tools/perf_report.py` from a run of "
             "`scripts/run_benchmarks.sh`. All figures are measured in "
             "Verilator simulation on the pipelined core; benchmarks are "
             "self-checking, so only architecturally correct runs appear here.")
    L.append("")

    L.append("## Cycles per instruction")
    L.append("")
    L.append("| benchmark | CPI (no prediction) | CPI (bimodal) | CPI (gshare) | best speedup |")
    L.append("|---|---|---|---|---|")
    for b in sorted(data):
        m = data[b]
        if not all(k in m for k in MODES):
            continue
        base = m["off"]["cpi"]
        best = min(m["bimodal"]["cpi"], m["gshare"]["cpi"])
        L.append(f"| `{b}` | {base:.3f} | {m['bimodal']['cpi']:.3f} | "
                 f"{m['gshare']['cpi']:.3f} | {base / best:.2f}x |")
    L.append("")

    L.append("## Branch prediction accuracy")
    L.append("")
    L.append("| benchmark | branches | taken | mispredict (none) | bimodal | gshare |")
    L.append("|---|---|---|---|---|---|")
    for b in sorted(data):
        m = data[b]
        if not all(k in m for k in MODES):
            continue
        br = m["off"]["branches"]
        if br == 0:
            continue
        pct = lambda mode: 100.0 * m[mode]["mispredicts"] / br
        L.append(f"| `{b}` | {br} | {100.0 * m['off']['taken'] / br:.1f}% | "
                 f"{pct('off'):.1f}% | {pct('bimodal'):.1f}% | {pct('gshare'):.1f}% |")
    L.append("")

    L.append("## Where the cycles go (best predictor mode)")
    L.append("")
    L.append("| benchmark | mode | cycles | retired | load-use stalls | MDU stalls | flush cycles | other |")
    L.append("|---|---|---|---|---|---|---|---|")
    for b in sorted(data):
        m = data[b]
        if not all(k in m for k in MODES):
            continue
        mode = min(MODES[1:], key=lambda k: m[k]["cpi"])
        r = m[mode]
        flush = 2 * r["redirects"]          # each redirect squashes two stages
        other = r["cycles"] - r["retired"] - r["stall_loaduse"] - r["stall_mdu"] - flush
        f = lambda v: f"{v} ({100.0 * v / r['cycles']:.1f}%)"
        L.append(f"| `{b}` | {mode} | {r['cycles']} | {f(r['retired'])} | "
                 f"{f(r['stall_loaduse'])} | {f(r['stall_mdu'])} | {f(flush)} | {f(other)} |")
    L.append("")
    L.append("*\"other\" is reset/startup cycles plus any cycle in which the "
             "final stage held no valid instruction for reasons already counted "
             "upstream; it is reported rather than hidden so the columns are "
             "auditable against the total.*")
    L.append("")

    text = "\n".join(L) + "\n"
    if a.out == "-":
        print(text, end="")
    else:
        open(a.out, "w").write(text)
        print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
